################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
# footer content
[en.params]
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."

################################### Italian language #####################################
[it]
languageName = "It"
languageCode = "it-it"
contentDir = "content/italian"
weight = 1
# footer content
[it.params]
footer_content = "CentroTavola è un progetto editoriale dedicato al racconto del mondo della ristorazione attraverso le voci dei suoi protagonisti. Un viaggio tra cucine, storie e sapori dell'enogastronomia italiana."
