# Start of Selection
############### Navigazione Italiana ################

[[main]]
name = "Chi Siamo"
url = "about/"
weight = 2

[[main]]
name = "Contatti"
url = "contact/"
weight = 3

# Menu a discesa
[[main]]
weight = 4
name = "Pagine"
hasChildren = true

[[main]]
parent = "Pagine"
name = "Autore"
url = "author/john-doe/"
weight = 1

[[main]]
parent = "Pagine"
name = "Categoria"
url = "categories/photography/"
weight = 2

[[main]]
parent = "Pagine"
name = "Tag"
url = "tags/photo/"
weight = 3

[[main]]
parent = "Pagine"
name = "Cerca"
url = "search/"
weight = 4

[[main]]
parent = "Pagine"
name = "Pagina 404"
url = "404/"
weight = 5

[[main]]
parent = "Pagine"
name = "Elementi"
url = "elements/"
weight = 6

# menu footer
[[footer]]
name = "Chi Siamo"
url = "about/"
weight = 1

[[footer]]
name = "Contatti"
url = "contact/"
weight = 2

[[footer]]
name = "Informativa sulla Privacy"
url = "privacy-policy/"
weight = 3

[[footer]]
name = "Termini e Condizioni"
url = "terms-conditions/"
weight = 4
# End of Selection