# Start of Selection
############### Navigazione Italiana ################

# Menu a discesa per le categorie
[[main]]
name = "Categorie"
weight = 1
hasChildren = true

[[main]]
parent = "Categorie"
name = "Eventi"
url = "categories/eventi/"
weight = 1

[[main]]
parent = "Categorie"
name = "News"
url = "categories/news/"
weight = 2

[[main]]
parent = "Categorie"
name = "Ristoranti"
url = "categories/ristoranti/"
weight = 3

[[main]]
parent = "Categorie"
name = "Le ricette dello chef"
url = "categories/le-ricette-dello-chef/"
weight = 4

[[main]]
parent = "Categorie"
name = "In buone mani"
url = "categories/in-buone-mani/"
weight = 5

[[main]]
parent = "Categorie"
name = "Aziende e Prodotti"
url = "categories/aziende-e-prodotti/"
weight = 6

# Sezioni con form contatti
[[main]]
name = "Promuovi la tua attività"
url = "promuovi/"
weight = 7

[[main]]
name = "Organizza il tuo tour in Tuscia"
url = "organizza-tour/"
weight = 8

# menu footer
[[footer]]
name = "Chi Siamo"
url = "about/"
weight = 1

[[footer]]
name = "Contatti"
url = "contact/"
weight = 2

[[footer]]
name = "Informativa sulla Privacy"
url = "privacy-policy/"
weight = 3

[[footer]]
name = "Termini e Condizioni"
url = "terms-conditions/"
weight = 4
# End of Selection