[[main]]
name = "Categorie"
weight = 1
hasChildren = true

[[main]]
name = "Eventi"
url = "categories/eventi/"
weight = 1
parent = "Categorie"

[[main]]
name = "News"
url = "categories/news/"
weight = 2
parent = "Categorie"

[[main]]
name = "Ristoranti"
url = "categories/ristoranti/"
weight = 3
parent = "Categorie"

[[main]]
name = "Ricette degli chef"
url = "categories/ricette-degli-chef/"
weight = 4
parent = "Categorie"

[[main]]
name = "In buone mani"
url = "categories/in-buone-mani/"
weight = 5
parent = "Categorie"

[[main]]
name = "Aziende e prodotti"
url = "categories/aziende-e-prodotti/"
weight = 6
parent = "Categorie"

[[main]]
name = "Promuovi la tua attività"
url = "promuovi/"
weight = 7

[[main]]
name = "Organizza il tuo tour in Tuscia"
url = "organizza-tour/"
weight = 8

[[footer]]
name = "Chi Siamo"
url = "about/"
weight = 1

[[footer]]
name = "Contatti"
url = "contact/"
weight = 2

[[footer]]
name = "Informativa sulla Privacy"
url = "privacy-policy/"
weight = 3

[[footer]]
name = "Termini e Condizioni"
url = "terms-conditions/"
weight = 4
