page_not_found_image = "images/404.png"
logo_webp = true
purge_css = true
mainSections = [ "post" ]
featured_post = true
post_layout = "grid"
sidebar = "right"
contact_form_action = "#"
google_tag_manager = ""
custom_script = ""
theme_copyright = false
logo = "/images/centro-tavola-logo-2.png"
favicon = "/images/CentroTavolalogonew.png"
logo_width = "400px"
logo_text = "Centro Tavola"
copyright = "Copyright by Alessandro Creta"

[preloader]
enable = true
preloader = ""

[search]
enable = true
primary_color = "#ce8460"
include_sections = [ "post", "shop" ]
show_image = true
show_description = true
show_tags = true
show_categories = true
input_placeholder = "Cerca su CentroTavola"
empty_results_placeholder = "Cerca su CentroTavola"

[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

[snipcart]
enable = true
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
currency = "$"

[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d"

[valine_comment]
enable = false
appId = ""
appKey = ""
avatar = ""
pageSize = 10
visitor = true
highlight = true
recordIP = true
enableQQ = false

[matomo]
enable = false
url = ""
id = ""

[baidu]
enable = false
analytics_id = ""

[plausible]
enable = false
domain = ""

[counter]
enable = false
username = ""

[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""
mastodon = ""

[widgets]
sidebar = [
  "search",
  "about-me",
  "promotion",
  "subscription",
  "categories",
  "recent-post",
  "social"
]

[contact_info]
address = ""
mobile = ""
email = "centrotavolamail@gmail.com"

[promotion]
enable = true
image = "/images/banner side 2.png"
link = "https://www.officinavisiva.it"

[top_promotion]
enable = true
image = "/images/Località Borghetto, spiaggia di Grotte di Castro (VT).jpg"
link = "https://ristoranteilcapriccio.it"

[metadata]
keywords = [ "Boilerplate", "Hugo", "Themefisher", "GetHugoThemes" ]
description = "This is meta description"
author = "Themefisher"
image = "/images/favicon.png"

[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://www.facebook.com/alessandro.creta.3"

[[social]]
title = "instagram"
icon = "fab fa-instagram"
link = "https://www.instagram.com/cretalex"

[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
